version: '3'
services:
  apollo:
    image: apollo_base
    build: ./api
    depends_on:
      - arangodb
      - memcached
    hostname: ${APOLLO_HOST}
    env_file: .env
    ports:
      - "${APOLLO_PORT}:${APOLLO_PORT}"
  client:
    image: client_base 
    build: 
      context: ./client
      args: 
        - VUE_APP_PROXY_URI=${PROXY_URI}
        - VUE_APP_PROXY_PORT=${PROXY_HTTP_PORT}
        - VUE_APP_APOLLO_HOST=${APOLLO_HOST}
        - VUE_APP_AUTH_HOST=${AUTH_HOST}
        - VUE_APP_SHARE_HOST=${SHARE_HOST}
        - VUE_APP_KEY=${CLIENT_KEY}
        - VUE_APP_SECRET=${CLIENT_SECRET}
        - PORT=${CLIENT_PORT}
        - NODE_ENV=${NODE_ENV}
        - VUE_APP_ANALYTICS=${CLIENT_ANALYTICS}
    depends_on:
      - apollo
      - auth
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    hostname: ${CLIENT_HOST}
      
  arangodb:
    hostname: ${ARANGODB_HOST}
    image: arangodb/arangodb
    ports:
      - "${ARANGODB_PORT}:8529"
    # volume does not work with windows
    volumes:
      - ${ARANGODB_VOLUME}:/var/lib/arangodb3
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGODB_PASSWORD}
  auth:
    hostname: ${AUTH_HOST}
    image: auth_base
    build: ./auth
    ports:
      - "${AUTH_PORT}:4000"
    env_file: .env
  proxy:
    hostname: proxy
    image: proxy_base
    build: ./server
    env_file: .env
    ports:
      - "${PROXY_HTTP_PORT}:80"
      - "${PROXY_HTTPS_PORT}:443"
    volumes:
      - ${PROXY_ERROR_LOG_LOC}:/etc/nginx/error_log.log
      - ${PROXY_CACHE_LOC}:/etc/nginx/cache
      - ${PROXY_LETSENCRYPT_LOC}:/etc/letsencrypt/
    depends_on:
      - auth
      - client
      - apollo
      - share
  memcached:
    hostname: ${MEMCACHED_HOST}
    image: memcached:alpine
    ports:
      - "11211:11211"
  share:
    hostname: ${SHARE_HOST}
    depends_on: 
      - arangodb
    ports:
      - "${SHARE_PORT}:${SHARE_PORT}"
    build:
      context: ./services/share
      args:
        - SHARE_PORT:${SHARE_PORT}
    env_file: .env

networks:
  default:
    driver: bridge
