version: '3'
services:
  apollo:
    ports:
      - "3003"
  client:
    ports:
      - "8080"
      
  arangodb:
    ports:
      - "8529"
  auth:
    ports:
      - "$4000"
  proxy:
    ports:
      - "80:80"
      - "443:443"
  memcached:
    ports:
      - "11211"
  share:
    ports:
      - "4444"
