version: "3"
services:
  apollo:
    image: ghcr.io/out-of-tune/apollo:latest
    ports:
      - "3003"
  client:
    image: ghcr.io/out-of-tune/client:latest
    ports:
      - "8080"
  arangodb:
    ports:
      - "8529"
  auth:
    image: ghcr.io/out-of-tune/auth:latest
    ports:
      - "4000"
  proxy:
    image: ghcr.io/out-of-tune/proxy:latest
    ports:
      - "${PROXY_HTTP_PORT}:80"
      - "${PROXY_HTTPS_PORT}:443"
  memcached:
    ports:
      - "11211"
  share:
    image: ghcr.io/out-of-tune/share:latest
    ports:
      - "4444"
