version: '3'
services:
  apollo:
    ports:
      - "${APOLLO_PORT}"
  client:
    ports:
      - "${CLIENT_PORT}"
      
  arangodb:
    ports:
      - "${ARANGODB_PORT}"
  auth:
    ports:
      - "${AUTH_PORT}"
  proxy:
    ports:
      - "${PROXY_HTTP_PORT}:${PROXY_HTTP_PORT}"
      - "${PROXY_HTTPS_PORT}:${PROXY_HTTPS_PORT}"
  memcached:
    ports:
      - "11211"
  share:
    ports:
      - "${SHARE_PORT}"
