version: '3'
services:
  apollo:
    image: ghcr.io/out-of-tune/apollo:nightly
    ports:
      - "3003"
  client:
    image: ghcr.io/out-of-tune/client:nightly
    ports:
      - "8080"
  arangodb:
    ports:
      - "8529"
  auth:
    image: ghcr.io/out-of-tune/auth:nightly
    ports:
      - "4000"
  proxy:
    image: ghcr.io/out-of-tune/proxy:nightly
    ports:
      - "${PROXY_HTTP_PORT}:80"
      - "${PROXY_HTTPS_PORT}:443"
  memcached:
    ports:
      - "11211"
  share:
    image: ghcr.io/out-of-tune/share:nightly
    ports:
      - "4444"
