version: '3'
services:
  apollo:
    image: apollo_base
    build: ./api
    depends_on:
      - arangodb
      - memcached
    env_file: .env
  client:
    image: client_base 
    build: 
      context: ./client
      args: 
        - VUE_APP_PROXY_URI=${PROXY_URI}
        - NODE_ENV=${NODE_ENV}
    depends_on:
      - apollo
      - auth
      
  arangodb:
    image: arangodb/arangodb
    volumes:
      - ${ARANGODB_VOLUME}:/var/lib/arangodb3
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGODB_PASSWORD}
  auth:
    image: auth_base
    build: ./auth
    env_file: .env
  proxy:
    image: proxy_base
    build: ./server
    env_file: .env
    volumes:
      - ${PROXY_ERROR_LOG_LOC}:/etc/nginx/error_log.log
      - ${PROXY_CACHE_LOC}:/etc/nginx/cache
      - ${PROXY_LETSENCRYPT_LOC}:/etc/letsencrypt/
    depends_on:
      - auth
      - client
      - apollo
      - share
  memcached:
    image: memcached:alpine
  share:
    depends_on: 
      - arangodb
    build:
      context: ./services/share
      args:
        - SHARE_PORT:4444
    env_file: .env

networks:
  default:
    driver: bridge
