// @ts-nocheck
/* eslint-disable */
// Generated by antlr-ng from AdvancedSearch.g4. Run `npm run generate:parser` to update.

import type {
  ErrorNode,
  ParseTreeListener,
  ParserRuleContext,
  TerminalNode,
} from "antlr4ng";

import { NodeTypeContext } from "./AdvancedSearchParser.js";
import { AttributeSearchContext } from "./AdvancedSearchParser.js";
import { AttributeDataContext } from "./AdvancedSearchParser.js";
import { AttributeContext } from "./AdvancedSearchParser.js";
import { AttributesContext } from "./AdvancedSearchParser.js";
import { SearchPartContext } from "./AdvancedSearchParser.js";
import { SearchContext } from "./AdvancedSearchParser.js";

/**
 * This interface defines a complete listener for a parse tree produced by
 * `AdvancedSearchParser`.
 */
export class AdvancedSearchListener implements ParseTreeListener {
  /**
   * Enter a parse tree produced by `AdvancedSearchParser.nodeType`.
   * @param ctx the parse tree
   */
  enterNodeType?: (ctx: NodeTypeContext) => void;
  /**
   * Exit a parse tree produced by `AdvancedSearchParser.nodeType`.
   * @param ctx the parse tree
   */
  exitNodeType?: (ctx: NodeTypeContext) => void;
  /**
   * Enter a parse tree produced by `AdvancedSearchParser.attributeSearch`.
   * @param ctx the parse tree
   */
  enterAttributeSearch?: (ctx: AttributeSearchContext) => void;
  /**
   * Exit a parse tree produced by `AdvancedSearchParser.attributeSearch`.
   * @param ctx the parse tree
   */
  exitAttributeSearch?: (ctx: AttributeSearchContext) => void;
  /**
   * Enter a parse tree produced by `AdvancedSearchParser.attributeData`.
   * @param ctx the parse tree
   */
  enterAttributeData?: (ctx: AttributeDataContext) => void;
  /**
   * Exit a parse tree produced by `AdvancedSearchParser.attributeData`.
   * @param ctx the parse tree
   */
  exitAttributeData?: (ctx: AttributeDataContext) => void;
  /**
   * Enter a parse tree produced by `AdvancedSearchParser.attribute`.
   * @param ctx the parse tree
   */
  enterAttribute?: (ctx: AttributeContext) => void;
  /**
   * Exit a parse tree produced by `AdvancedSearchParser.attribute`.
   * @param ctx the parse tree
   */
  exitAttribute?: (ctx: AttributeContext) => void;
  /**
   * Enter a parse tree produced by `AdvancedSearchParser.attributes`.
   * @param ctx the parse tree
   */
  enterAttributes?: (ctx: AttributesContext) => void;
  /**
   * Exit a parse tree produced by `AdvancedSearchParser.attributes`.
   * @param ctx the parse tree
   */
  exitAttributes?: (ctx: AttributesContext) => void;
  /**
   * Enter a parse tree produced by `AdvancedSearchParser.searchPart`.
   * @param ctx the parse tree
   */
  enterSearchPart?: (ctx: SearchPartContext) => void;
  /**
   * Exit a parse tree produced by `AdvancedSearchParser.searchPart`.
   * @param ctx the parse tree
   */
  exitSearchPart?: (ctx: SearchPartContext) => void;
  /**
   * Enter a parse tree produced by `AdvancedSearchParser.search`.
   * @param ctx the parse tree
   */
  enterSearch?: (ctx: SearchContext) => void;
  /**
   * Exit a parse tree produced by `AdvancedSearchParser.search`.
   * @param ctx the parse tree
   */
  exitSearch?: (ctx: SearchContext) => void;

  visitTerminal(node: TerminalNode): void {}
  visitErrorNode(node: ErrorNode): void {}
  enterEveryRule(node: ParserRuleContext): void {}
  exitEveryRule(node: ParserRuleContext): void {}
}
