// @ts-nocheck
/* eslint-disable */
// Generated by antlr-ng from AdvancedSearch.g4. Run `npm run generate:parser` to update.

import * as antlr from "antlr4ng";
import { Token } from "antlr4ng";

import { AdvancedSearchListener } from "./AdvancedSearchListener.js";
// for running tests with parameters, TODO: discuss strategy for typed parameters in CI
// eslint-disable-next-line no-unused-vars
type int = number;

export class AdvancedSearchParser extends antlr.Parser {
  public static readonly WORD = 1;
  public static readonly TEXT = 2;
  public static readonly DECIMAL = 3;
  public static readonly WHITESPACE = 4;
  public static readonly COLON = 5;
  public static readonly OPERATOR = 6;
  public static readonly OPENPARAN = 7;
  public static readonly CLOSEPARAN = 8;
  public static readonly RULE_nodeType = 0;
  public static readonly RULE_attributeSearch = 1;
  public static readonly RULE_attributeData = 2;
  public static readonly RULE_attribute = 3;
  public static readonly RULE_attributes = 4;
  public static readonly RULE_searchPart = 5;
  public static readonly RULE_search = 6;

  public static readonly literalNames = [];

  public static readonly symbolicNames = [
    null,
    "WORD",
    "TEXT",
    "DECIMAL",
    "WHITESPACE",
    "COLON",
    "OPERATOR",
    "OPENPARAN",
    "CLOSEPARAN",
  ];
  public static readonly ruleNames = [
    "nodeType",
    "attributeSearch",
    "attributeData",
    "attribute",
    "attributes",
    "searchPart",
    "search",
  ];

  public get grammarFileName(): string {
    return "AdvancedSearch.g4";
  }
  public get literalNames(): (string | null)[] {
    return AdvancedSearchParser.literalNames;
  }
  public get symbolicNames(): (string | null)[] {
    return AdvancedSearchParser.symbolicNames;
  }
  public get ruleNames(): string[] {
    return AdvancedSearchParser.ruleNames;
  }
  public get serializedATN(): number[] {
    return AdvancedSearchParser._serializedATN;
  }

  protected createFailedPredicateException(
    predicate?: string,
    message?: string,
  ): antlr.FailedPredicateException {
    return new antlr.FailedPredicateException(this, predicate, message);
  }

  public constructor(input: antlr.TokenStream) {
    super(input);
    this.interpreter = new antlr.ParserATNSimulator(
      this,
      AdvancedSearchParser._ATN,
      AdvancedSearchParser.decisionsToDFA,
      new antlr.PredictionContextCache(),
    );
  }
  public nodeType(): NodeTypeContext {
    let localContext = new NodeTypeContext(this.context, this.state);
    this.enterRule(localContext, 0, AdvancedSearchParser.RULE_nodeType);
    try {
      this.enterOuterAlt(localContext, 1);
      {
        this.state = 14;
        this.match(AdvancedSearchParser.WORD);
      }
    } catch (re) {
      if (re instanceof antlr.RecognitionException) {
        this.errorHandler.reportError(this, re);
        this.errorHandler.recover(this, re);
      } else {
        throw re;
      }
    } finally {
      this.exitRule();
    }
    return localContext;
  }
  public attributeSearch(): AttributeSearchContext {
    let localContext = new AttributeSearchContext(this.context, this.state);
    this.enterRule(localContext, 2, AdvancedSearchParser.RULE_attributeSearch);
    let _la: number;
    try {
      this.enterOuterAlt(localContext, 1);
      {
        this.state = 16;
        _la = this.tokenStream.LA(1);
        if (!(_la === 1 || _la === 2)) {
          this.errorHandler.recoverInline(this);
        } else {
          this.errorHandler.reportMatch(this);
          this.consume();
        }
      }
    } catch (re) {
      if (re instanceof antlr.RecognitionException) {
        this.errorHandler.reportError(this, re);
        this.errorHandler.recover(this, re);
      } else {
        throw re;
      }
    } finally {
      this.exitRule();
    }
    return localContext;
  }
  public attributeData(): AttributeDataContext {
    let localContext = new AttributeDataContext(this.context, this.state);
    this.enterRule(localContext, 4, AdvancedSearchParser.RULE_attributeData);
    let _la: number;
    try {
      this.enterOuterAlt(localContext, 1);
      {
        this.state = 18;
        _la = this.tokenStream.LA(1);
        if (!((_la & ~0x1f) === 0 && ((1 << _la) & 14) !== 0)) {
          this.errorHandler.recoverInline(this);
        } else {
          this.errorHandler.reportMatch(this);
          this.consume();
        }
      }
    } catch (re) {
      if (re instanceof antlr.RecognitionException) {
        this.errorHandler.reportError(this, re);
        this.errorHandler.recover(this, re);
      } else {
        throw re;
      }
    } finally {
      this.exitRule();
    }
    return localContext;
  }
  public attribute(): AttributeContext {
    let localContext = new AttributeContext(this.context, this.state);
    this.enterRule(localContext, 6, AdvancedSearchParser.RULE_attribute);
    try {
      this.enterOuterAlt(localContext, 1);
      {
        this.state = 20;
        this.attributeSearch();
        this.state = 21;
        this.match(AdvancedSearchParser.OPERATOR);
        this.state = 22;
        this.attributeData();
      }
    } catch (re) {
      if (re instanceof antlr.RecognitionException) {
        this.errorHandler.reportError(this, re);
        this.errorHandler.recover(this, re);
      } else {
        throw re;
      }
    } finally {
      this.exitRule();
    }
    return localContext;
  }
  public attributes(): AttributesContext {
    let localContext = new AttributesContext(this.context, this.state);
    this.enterRule(localContext, 8, AdvancedSearchParser.RULE_attributes);
    let _la: number;
    try {
      this.enterOuterAlt(localContext, 1);
      {
        this.state = 26;
        this.errorHandler.sync(this);
        _la = this.tokenStream.LA(1);
        do {
          {
            {
              this.state = 24;
              this.match(AdvancedSearchParser.WHITESPACE);
              this.state = 25;
              this.attribute();
            }
          }
          this.state = 28;
          this.errorHandler.sync(this);
          _la = this.tokenStream.LA(1);
        } while (_la === 4);
      }
    } catch (re) {
      if (re instanceof antlr.RecognitionException) {
        this.errorHandler.reportError(this, re);
        this.errorHandler.recover(this, re);
      } else {
        throw re;
      }
    } finally {
      this.exitRule();
    }
    return localContext;
  }
  public searchPart(): SearchPartContext {
    let localContext = new SearchPartContext(this.context, this.state);
    this.enterRule(localContext, 10, AdvancedSearchParser.RULE_searchPart);
    let _la: number;
    try {
      this.enterOuterAlt(localContext, 1);
      {
        this.state = 30;
        this.nodeType();
        this.state = 33;
        this.errorHandler.sync(this);
        _la = this.tokenStream.LA(1);
        if (_la === 5) {
          {
            this.state = 31;
            this.match(AdvancedSearchParser.COLON);
            this.state = 32;
            this.attributes();
          }
        }
      }
    } catch (re) {
      if (re instanceof antlr.RecognitionException) {
        this.errorHandler.reportError(this, re);
        this.errorHandler.recover(this, re);
      } else {
        throw re;
      }
    } finally {
      this.exitRule();
    }
    return localContext;
  }
  public search(): SearchContext {
    let localContext = new SearchContext(this.context, this.state);
    this.enterRule(localContext, 12, AdvancedSearchParser.RULE_search);
    let _la: number;
    try {
      this.enterOuterAlt(localContext, 1);
      {
        this.state = 38;
        this.errorHandler.sync(this);
        _la = this.tokenStream.LA(1);
        while (_la === 1) {
          {
            {
              this.state = 35;
              this.searchPart();
            }
          }
          this.state = 40;
          this.errorHandler.sync(this);
          _la = this.tokenStream.LA(1);
        }
      }
    } catch (re) {
      if (re instanceof antlr.RecognitionException) {
        this.errorHandler.reportError(this, re);
        this.errorHandler.recover(this, re);
      } else {
        throw re;
      }
    } finally {
      this.exitRule();
    }
    return localContext;
  }

  public static readonly _serializedATN: number[] = [
    4, 1, 8, 42, 2, 0, 7, 0, 2, 1, 7, 1, 2, 2, 7, 2, 2, 3, 7, 3, 2, 4, 7, 4, 2,
    5, 7, 5, 2, 6, 7, 6, 1, 0, 1, 0, 1, 1, 1, 1, 1, 2, 1, 2, 1, 3, 1, 3, 1, 3,
    1, 3, 1, 4, 1, 4, 4, 4, 27, 8, 4, 11, 4, 12, 4, 28, 1, 5, 1, 5, 1, 5, 3, 5,
    34, 8, 5, 1, 6, 5, 6, 37, 8, 6, 10, 6, 12, 6, 40, 9, 6, 1, 6, 0, 0, 7, 0, 2,
    4, 6, 8, 10, 12, 0, 2, 1, 0, 1, 2, 1, 0, 1, 3, 37, 0, 14, 1, 0, 0, 0, 2, 16,
    1, 0, 0, 0, 4, 18, 1, 0, 0, 0, 6, 20, 1, 0, 0, 0, 8, 26, 1, 0, 0, 0, 10, 30,
    1, 0, 0, 0, 12, 38, 1, 0, 0, 0, 14, 15, 5, 1, 0, 0, 15, 1, 1, 0, 0, 0, 16,
    17, 7, 0, 0, 0, 17, 3, 1, 0, 0, 0, 18, 19, 7, 1, 0, 0, 19, 5, 1, 0, 0, 0,
    20, 21, 3, 2, 1, 0, 21, 22, 5, 6, 0, 0, 22, 23, 3, 4, 2, 0, 23, 7, 1, 0, 0,
    0, 24, 25, 5, 4, 0, 0, 25, 27, 3, 6, 3, 0, 26, 24, 1, 0, 0, 0, 27, 28, 1, 0,
    0, 0, 28, 26, 1, 0, 0, 0, 28, 29, 1, 0, 0, 0, 29, 9, 1, 0, 0, 0, 30, 33, 3,
    0, 0, 0, 31, 32, 5, 5, 0, 0, 32, 34, 3, 8, 4, 0, 33, 31, 1, 0, 0, 0, 33, 34,
    1, 0, 0, 0, 34, 11, 1, 0, 0, 0, 35, 37, 3, 10, 5, 0, 36, 35, 1, 0, 0, 0, 37,
    40, 1, 0, 0, 0, 38, 36, 1, 0, 0, 0, 38, 39, 1, 0, 0, 0, 39, 13, 1, 0, 0, 0,
    40, 38, 1, 0, 0, 0, 3, 28, 33, 38,
  ];

  private static __ATN: antlr.ATN;
  public static get _ATN(): antlr.ATN {
    if (!AdvancedSearchParser.__ATN) {
      AdvancedSearchParser.__ATN = new antlr.ATNDeserializer().deserialize(
        AdvancedSearchParser._serializedATN,
      );
    }

    return AdvancedSearchParser.__ATN;
  }

  private static readonly vocabulary = new antlr.Vocabulary(
    AdvancedSearchParser.literalNames,
    AdvancedSearchParser.symbolicNames,
    [],
  );

  public override get vocabulary(): antlr.Vocabulary {
    return AdvancedSearchParser.vocabulary;
  }

  private static readonly decisionsToDFA =
    AdvancedSearchParser._ATN.decisionToState.map(
      (ds: antlr.DecisionState, index: number) => new antlr.DFA(ds, index),
    );
}

export class NodeTypeContext extends antlr.ParserRuleContext {
  public constructor(
    parent: antlr.ParserRuleContext | null,
    invokingState: number,
  ) {
    super(parent, invokingState);
  }
  public WORD(): antlr.TerminalNode {
    return this.getToken(AdvancedSearchParser.WORD, 0)!;
  }
  public override get ruleIndex(): number {
    return AdvancedSearchParser.RULE_nodeType;
  }
  public override enterRule(listener: AdvancedSearchListener): void {
    if (listener.enterNodeType) {
      listener.enterNodeType(this);
    }
  }
  public override exitRule(listener: AdvancedSearchListener): void {
    if (listener.exitNodeType) {
      listener.exitNodeType(this);
    }
  }
}

export class AttributeSearchContext extends antlr.ParserRuleContext {
  public constructor(
    parent: antlr.ParserRuleContext | null,
    invokingState: number,
  ) {
    super(parent, invokingState);
  }
  public WORD(): antlr.TerminalNode | null {
    return this.getToken(AdvancedSearchParser.WORD, 0);
  }
  public TEXT(): antlr.TerminalNode | null {
    return this.getToken(AdvancedSearchParser.TEXT, 0);
  }
  public override get ruleIndex(): number {
    return AdvancedSearchParser.RULE_attributeSearch;
  }
  public override enterRule(listener: AdvancedSearchListener): void {
    if (listener.enterAttributeSearch) {
      listener.enterAttributeSearch(this);
    }
  }
  public override exitRule(listener: AdvancedSearchListener): void {
    if (listener.exitAttributeSearch) {
      listener.exitAttributeSearch(this);
    }
  }
}

export class AttributeDataContext extends antlr.ParserRuleContext {
  public constructor(
    parent: antlr.ParserRuleContext | null,
    invokingState: number,
  ) {
    super(parent, invokingState);
  }
  public WORD(): antlr.TerminalNode | null {
    return this.getToken(AdvancedSearchParser.WORD, 0);
  }
  public TEXT(): antlr.TerminalNode | null {
    return this.getToken(AdvancedSearchParser.TEXT, 0);
  }
  public DECIMAL(): antlr.TerminalNode | null {
    return this.getToken(AdvancedSearchParser.DECIMAL, 0);
  }
  public override get ruleIndex(): number {
    return AdvancedSearchParser.RULE_attributeData;
  }
  public override enterRule(listener: AdvancedSearchListener): void {
    if (listener.enterAttributeData) {
      listener.enterAttributeData(this);
    }
  }
  public override exitRule(listener: AdvancedSearchListener): void {
    if (listener.exitAttributeData) {
      listener.exitAttributeData(this);
    }
  }
}

export class AttributeContext extends antlr.ParserRuleContext {
  public constructor(
    parent: antlr.ParserRuleContext | null,
    invokingState: number,
  ) {
    super(parent, invokingState);
  }
  public attributeSearch(): AttributeSearchContext {
    return this.getRuleContext(0, AttributeSearchContext)!;
  }
  public OPERATOR(): antlr.TerminalNode {
    return this.getToken(AdvancedSearchParser.OPERATOR, 0)!;
  }
  public attributeData(): AttributeDataContext {
    return this.getRuleContext(0, AttributeDataContext)!;
  }
  public override get ruleIndex(): number {
    return AdvancedSearchParser.RULE_attribute;
  }
  public override enterRule(listener: AdvancedSearchListener): void {
    if (listener.enterAttribute) {
      listener.enterAttribute(this);
    }
  }
  public override exitRule(listener: AdvancedSearchListener): void {
    if (listener.exitAttribute) {
      listener.exitAttribute(this);
    }
  }
}

export class AttributesContext extends antlr.ParserRuleContext {
  public constructor(
    parent: antlr.ParserRuleContext | null,
    invokingState: number,
  ) {
    super(parent, invokingState);
  }
  public WHITESPACE(): antlr.TerminalNode[];
  public WHITESPACE(i: number): antlr.TerminalNode | null;
  public WHITESPACE(
    i?: number,
  ): antlr.TerminalNode | null | antlr.TerminalNode[] {
    if (i === undefined) {
      return this.getTokens(AdvancedSearchParser.WHITESPACE);
    } else {
      return this.getToken(AdvancedSearchParser.WHITESPACE, i);
    }
  }
  public attribute(): AttributeContext[];
  public attribute(i: number): AttributeContext | null;
  public attribute(i?: number): AttributeContext[] | AttributeContext | null {
    if (i === undefined) {
      return this.getRuleContexts(AttributeContext);
    }

    return this.getRuleContext(i, AttributeContext);
  }
  public override get ruleIndex(): number {
    return AdvancedSearchParser.RULE_attributes;
  }
  public override enterRule(listener: AdvancedSearchListener): void {
    if (listener.enterAttributes) {
      listener.enterAttributes(this);
    }
  }
  public override exitRule(listener: AdvancedSearchListener): void {
    if (listener.exitAttributes) {
      listener.exitAttributes(this);
    }
  }
}

export class SearchPartContext extends antlr.ParserRuleContext {
  public constructor(
    parent: antlr.ParserRuleContext | null,
    invokingState: number,
  ) {
    super(parent, invokingState);
  }
  public nodeType(): NodeTypeContext {
    return this.getRuleContext(0, NodeTypeContext)!;
  }
  public COLON(): antlr.TerminalNode | null {
    return this.getToken(AdvancedSearchParser.COLON, 0);
  }
  public attributes(): AttributesContext | null {
    return this.getRuleContext(0, AttributesContext);
  }
  public override get ruleIndex(): number {
    return AdvancedSearchParser.RULE_searchPart;
  }
  public override enterRule(listener: AdvancedSearchListener): void {
    if (listener.enterSearchPart) {
      listener.enterSearchPart(this);
    }
  }
  public override exitRule(listener: AdvancedSearchListener): void {
    if (listener.exitSearchPart) {
      listener.exitSearchPart(this);
    }
  }
}

export class SearchContext extends antlr.ParserRuleContext {
  public constructor(
    parent: antlr.ParserRuleContext | null,
    invokingState: number,
  ) {
    super(parent, invokingState);
  }
  public searchPart(): SearchPartContext[];
  public searchPart(i: number): SearchPartContext | null;
  public searchPart(
    i?: number,
  ): SearchPartContext[] | SearchPartContext | null {
    if (i === undefined) {
      return this.getRuleContexts(SearchPartContext);
    }

    return this.getRuleContext(i, SearchPartContext);
  }
  public override get ruleIndex(): number {
    return AdvancedSearchParser.RULE_search;
  }
  public override enterRule(listener: AdvancedSearchListener): void {
    if (listener.enterSearch) {
      listener.enterSearch(this);
    }
  }
  public override exitRule(listener: AdvancedSearchListener): void {
    if (listener.exitSearch) {
      listener.exitSearch(this);
    }
  }
}
