name: Build and Deploy Docker Images

on:
  workflow_call:
    inputs:
      version:
        description: 'docker-image version to push'
        required: true
        type: string
      latest:
        description: 'whether to also tag and push the images as :latest'
        default: false
        type: boolean
        required: false

env:
  APP_MOUNT_PATH: "/app"
  PROXY_URI: "https://d.out-of-tune.org/app"
  NODE_ENV: "production"

jobs:
  matrix_maker:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.services }}
    steps:
      - uses: actions/checkout@v3
      - name: Find Dockerimages to build
        id: set-matrix
        #run: echo $(find -name Dockerfile | tr '\n' ' ')
        run: echo 'services=["client", "apollo", "auth", "share", "proxy"]' >> "$GITHUB_OUTPUT"
      - name: Debug output
        run: echo "${{ steps.set-matrix.outputs.services }}"

  build:
    needs: matrix_maker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJSON(needs.matrix_maker.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image ${{ matrix.service }}
        run: docker compose -f docker-compose.build.yml build ${{ matrix.service }}

      - name: Tag ${{ matrix.service }}:${{ inputs.version }}
        run: docker tag oot-${{ matrix.service }} ghcr.io/out-of-tune/${{ matrix.service }}:${{ inputs.version }}
      - name: Push ${{ matrix.service }}:${{ inputs.version }}
        run: docker push ghcr.io/out-of-tune/${{ matrix.service }}:${{ inputs.version }}

      - if: ${{ inputs.latest }}
        name: Tag ${{ matrix.service }}:latest
        run: docker tag oot-${{ matrix.service }} ghcr.io/out-of-tune/${{ matrix.service }}:latest
      - if: ${{ inputs.latest }}
        name: Push ${{ matrix.service }}:latest
        run: docker push ghcr.io/out-of-tune/${{ matrix.service }}:latest
