name: Docker Image CI

on:
  push:
    branches: [ "cicd/add-github-actions" ]
  pull_request:
    branches: [ "cicd/add-github-actions" ]

jobs:
  matrix_maker:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.result }}
    steps:
    - uses: actions/checkout@v3
    - name: Find Dockerimages to build
      id: set-matrix
      #run: echo $(find -name Dockerfile | tr '\n' ' ')
      run: echo '["./server/Dockerfile", "./client/Dockerfile", "./auth/Dockerfile", "./db/arango/Dockerfile", "./services/share/Dockerfile", "./api/Dockerfile"]'
    - name: Debug output
      run: echo "${{ steps.set-matrix.outputs.result }}"
      

  build:
    needs: matrix_maker
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        file: ${{ fromJSON(needs.matrix_maker.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image (${{ matrix.file }})
      run: docker build $(dirname ${{ matrix.file }}) --file Dockerfile --tag $(basename $(dirname ${{ matrix.file }})):$(date +%s)
