name: Docker Image CI

on:
  push:
    branches: [ "cicd/add-github-actions" ]
  pull_request:
    branches: [ "cicd/add-github-actions" ]

jobs:
  matrix_maker:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.files }}
    steps:
    - uses: actions/checkout@v3
    - name: Find Dockerimages to build
      id: set-matrix
      #run: echo $(find -name Dockerfile | tr '\n' ' ')
      run: echo 'files=["./server/Dockerfile", "./client/Dockerfile", "./auth/Dockerfile", "./db/arango/Dockerfile", "./services/share/Dockerfile", "./api/Dockerfile"]' >> "$GITHUB_OUTPUT"
    - name: Debug output
      run: echo "${{ steps.set-matrix.outputs.files }}"
      

  build:
    needs: matrix_maker
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        file: ${{ fromJSON(needs.matrix_maker.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v3
    - name: Generate docker image tag
      id: docker-tag
      run: echo "tag=$(basename $(dirname ${{ matrix.file }}))" >> "$GITHUB_OUTPUT"
    - name: Generate docker image path
      id: docker-path
      run: echo "path=$(dirname ${{ matrix.file }})" >> "$GITHUB_OUTPUT"
    - name: Build the Docker image (${{ matrix.file }})
      run: docker build ${{ steps.docker-path.outputs.path }} --file Dockerfile --tag ${{ steps.docker-tag.outputs.tag}}:$(date +%s)
