name: Docker Image CI

on:
  push:
    branches: ["cicd/add-github-actions"]
  pull_request:
    branches: ["cicd/add-github-actions"]

env:
  VERSION: nightly
  BASE_URL: "/app"

jobs:
  matrix_maker:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.files }}
    steps:
      - uses: actions/checkout@v3
      - name: Find Dockerimages to build
        id: set-matrix
        #run: echo $(find -name Dockerfile | tr '\n' ' ')
        run: echo 'files=["./server/Dockerfile", "./client/Dockerfile", "./auth/Dockerfile", "./db/arango/Dockerfile", "./services/share/Dockerfile", "./api/Dockerfile"]' >> "$GITHUB_OUTPUT"
      - name: Debug output
        run: echo "${{ steps.set-matrix.outputs.files }}"

  build:
    needs: matrix_maker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJSON(needs.matrix_maker.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image ${{ matrix.file }}
        run: |
          cd $(dirname ${{ matrix.file }})
          IMAGE_NAME=$(basename $(dirname ${{ matrix.file }}))
          docker compose build ${{ matrix.file }}
          docker tag ${{ matrix.file }} ghcr.io/out-of-tune/$IMAGE_NAME:$VERSION 
          docker tag ${{ matrix.file }} ghcr.io/out-of-tune/$IMAGE_NAME:latest
          docker push ghcr.io/out-of-tune/$IMAGE_NAME:$VERSION

  test-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: npm
      - name: Install and run tests
        working-directory: ./client
        run: |
          npm ci
          npm run test

  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: npm
      - name: Install and run tests
        working-directory: ./api
        run: |
          npm ci
          npm run test
