name: Pipeline for Merge into Release

on:
  push:
    branches: [mock_release]

jobs:
  test:
    uses: ./.github/workflows/tests.yml
  deploy-nightly:
    needs: test
    uses: ./.github/workflows/docker-deploy.yml
    with:
      version: latest
